import unittest

import wfdb

from feature_extractor import get_structured_lead_features
from train_12ECG_classifier import hea_fp_to_np_array


class TestFeatureExtractor(unittest.TestCase):
    def test_get_structured_lead_features(self):
        r = wfdb.rdrecord("tests/data/A5432")

        sig_len, num_leads = r.p_signal.shape

        ir_cols = [
            "ECG_Rate_Mean",
            "HRV_RMSSD",
            "HRV_MeanNN",
            "HRV_SDNN",
            "HRV_SDSD",
            "HRV_CVNN",
            "HRV_CVSD",
            "HRV_MedianNN",
            "HRV_MadNN",
            "HRV_MCVNN",
            "HRV_pNN50",
            "HRV_pNN20",
            "HRV_TINN",
            "HRV_HTI",
            "HRV_ULF",
            "HRV_VLF",
            "HRV_LF",
            "HRV_HF",
            "HRV_VHF",
            "HRV_LFHF",
            "HRV_LFn",
            "HRV_HFn",
            "HRV_LnHF",
            "HRV_SD1",
            "HRV_SD2",
            "HRV_SD2SD1",
            "HRV_CSI",
            "HRV_CVI",
            "HRV_CSI_Modified",
            "HRV_SampEn",
        ]

        for lead_idx in range(num_leads):
            lead_sig = r.p_signal[:, lead_idx]
            lead_name = r.sig_name[lead_idx]
            data, dtype = get_structured_lead_features(
                lead_sig, sampling_rate=r.fs, lead_name=lead_name,
            )

            self.assertEqual(len(data), 30)

            self.assertCountEqual(
                [d[0] for d in dtype], [f"{lead_name}_{ir_col}" for ir_col in ir_cols]
            )

    def test_hea_fp_to_np_array(self):
        str_arr = hea_fp_to_np_array("tests/data/A5432.hea")

        ref_dtype = [
            ("record_name", "<U50"),
            ("seq_len", "<f4"),
            ("sampling_rate", "<f4"),
            ("age", "<f4"),
            ("sex", "<f4"),
            ("dx", "O"),
            ("I_ECG_Rate_Mean", "<f8"),
            ("I_HRV_RMSSD", "<f8"),
            ("I_HRV_MeanNN", "<f8"),
            ("I_HRV_SDNN", "<f8"),
            ("I_HRV_SDSD", "<f8"),
            ("I_HRV_CVNN", "<f8"),
            ("I_HRV_CVSD", "<f8"),
            ("I_HRV_MedianNN", "<f8"),
            ("I_HRV_MadNN", "<f8"),
            ("I_HRV_MCVNN", "<f8"),
            ("I_HRV_pNN50", "<f8"),
            ("I_HRV_pNN20", "<f8"),
            ("I_HRV_TINN", "<f8"),
            ("I_HRV_HTI", "<f8"),
            ("I_HRV_ULF", "<f8"),
            ("I_HRV_VLF", "<f8"),
            ("I_HRV_LF", "<f8"),
            ("I_HRV_HF", "<f8"),
            ("I_HRV_VHF", "<f8"),
            ("I_HRV_LFHF", "<f8"),
            ("I_HRV_LFn", "<f8"),
            ("I_HRV_HFn", "<f8"),
            ("I_HRV_LnHF", "<f8"),
            ("I_HRV_SD1", "<f8"),
            ("I_HRV_SD2", "<f8"),
            ("I_HRV_SD2SD1", "<f8"),
            ("I_HRV_CSI", "<f8"),
            ("I_HRV_CVI", "<f8"),
            ("I_HRV_CSI_Modified", "<f8"),
            ("I_HRV_SampEn", "<f8"),
            ("II_ECG_Rate_Mean", "<f8"),
            ("II_HRV_RMSSD", "<f8"),
            ("II_HRV_MeanNN", "<f8"),
            ("II_HRV_SDNN", "<f8"),
            ("II_HRV_SDSD", "<f8"),
            ("II_HRV_CVNN", "<f8"),
            ("II_HRV_CVSD", "<f8"),
            ("II_HRV_MedianNN", "<f8"),
            ("II_HRV_MadNN", "<f8"),
            ("II_HRV_MCVNN", "<f8"),
            ("II_HRV_pNN50", "<f8"),
            ("II_HRV_pNN20", "<f8"),
            ("II_HRV_TINN", "<f8"),
            ("II_HRV_HTI", "<f8"),
            ("II_HRV_ULF", "<f8"),
            ("II_HRV_VLF", "<f8"),
            ("II_HRV_LF", "<f8"),
            ("II_HRV_HF", "<f8"),
            ("II_HRV_VHF", "<f8"),
            ("II_HRV_LFHF", "<f8"),
            ("II_HRV_LFn", "<f8"),
            ("II_HRV_HFn", "<f8"),
            ("II_HRV_LnHF", "<f8"),
            ("II_HRV_SD1", "<f8"),
            ("II_HRV_SD2", "<f8"),
            ("II_HRV_SD2SD1", "<f8"),
            ("II_HRV_CSI", "<f8"),
            ("II_HRV_CVI", "<f8"),
            ("II_HRV_CSI_Modified", "<f8"),
            ("II_HRV_SampEn", "<f8"),
            ("III_ECG_Rate_Mean", "<f8"),
            ("III_HRV_RMSSD", "<f8"),
            ("III_HRV_MeanNN", "<f8"),
            ("III_HRV_SDNN", "<f8"),
            ("III_HRV_SDSD", "<f8"),
            ("III_HRV_CVNN", "<f8"),
            ("III_HRV_CVSD", "<f8"),
            ("III_HRV_MedianNN", "<f8"),
            ("III_HRV_MadNN", "<f8"),
            ("III_HRV_MCVNN", "<f8"),
            ("III_HRV_pNN50", "<f8"),
            ("III_HRV_pNN20", "<f8"),
            ("III_HRV_TINN", "<f8"),
            ("III_HRV_HTI", "<f8"),
            ("III_HRV_ULF", "<f8"),
            ("III_HRV_VLF", "<f8"),
            ("III_HRV_LF", "<f8"),
            ("III_HRV_HF", "<f8"),
            ("III_HRV_VHF", "<f8"),
            ("III_HRV_LFHF", "<f8"),
            ("III_HRV_LFn", "<f8"),
            ("III_HRV_HFn", "<f8"),
            ("III_HRV_LnHF", "<f8"),
            ("III_HRV_SD1", "<f8"),
            ("III_HRV_SD2", "<f8"),
            ("III_HRV_SD2SD1", "<f8"),
            ("III_HRV_CSI", "<f8"),
            ("III_HRV_CVI", "<f8"),
            ("III_HRV_CSI_Modified", "<f8"),
            ("III_HRV_SampEn", "<f8"),
            ("aVR_ECG_Rate_Mean", "<f8"),
            ("aVR_HRV_RMSSD", "<f8"),
            ("aVR_HRV_MeanNN", "<f8"),
            ("aVR_HRV_SDNN", "<f8"),
            ("aVR_HRV_SDSD", "<f8"),
            ("aVR_HRV_CVNN", "<f8"),
            ("aVR_HRV_CVSD", "<f8"),
            ("aVR_HRV_MedianNN", "<f8"),
            ("aVR_HRV_MadNN", "<f8"),
            ("aVR_HRV_MCVNN", "<f8"),
            ("aVR_HRV_pNN50", "<f8"),
            ("aVR_HRV_pNN20", "<f8"),
            ("aVR_HRV_TINN", "<f8"),
            ("aVR_HRV_HTI", "<f8"),
            ("aVR_HRV_ULF", "<f8"),
            ("aVR_HRV_VLF", "<f8"),
            ("aVR_HRV_LF", "<f8"),
            ("aVR_HRV_HF", "<f8"),
            ("aVR_HRV_VHF", "<f8"),
            ("aVR_HRV_LFHF", "<f8"),
            ("aVR_HRV_LFn", "<f8"),
            ("aVR_HRV_HFn", "<f8"),
            ("aVR_HRV_LnHF", "<f8"),
            ("aVR_HRV_SD1", "<f8"),
            ("aVR_HRV_SD2", "<f8"),
            ("aVR_HRV_SD2SD1", "<f8"),
            ("aVR_HRV_CSI", "<f8"),
            ("aVR_HRV_CVI", "<f8"),
            ("aVR_HRV_CSI_Modified", "<f8"),
            ("aVR_HRV_SampEn", "<f8"),
            ("aVL_ECG_Rate_Mean", "<f8"),
            ("aVL_HRV_RMSSD", "<f8"),
            ("aVL_HRV_MeanNN", "<f8"),
            ("aVL_HRV_SDNN", "<f8"),
            ("aVL_HRV_SDSD", "<f8"),
            ("aVL_HRV_CVNN", "<f8"),
            ("aVL_HRV_CVSD", "<f8"),
            ("aVL_HRV_MedianNN", "<f8"),
            ("aVL_HRV_MadNN", "<f8"),
            ("aVL_HRV_MCVNN", "<f8"),
            ("aVL_HRV_pNN50", "<f8"),
            ("aVL_HRV_pNN20", "<f8"),
            ("aVL_HRV_TINN", "<f8"),
            ("aVL_HRV_HTI", "<f8"),
            ("aVL_HRV_ULF", "<f8"),
            ("aVL_HRV_VLF", "<f8"),
            ("aVL_HRV_LF", "<f8"),
            ("aVL_HRV_HF", "<f8"),
            ("aVL_HRV_VHF", "<f8"),
            ("aVL_HRV_LFHF", "<f8"),
            ("aVL_HRV_LFn", "<f8"),
            ("aVL_HRV_HFn", "<f8"),
            ("aVL_HRV_LnHF", "<f8"),
            ("aVL_HRV_SD1", "<f8"),
            ("aVL_HRV_SD2", "<f8"),
            ("aVL_HRV_SD2SD1", "<f8"),
            ("aVL_HRV_CSI", "<f8"),
            ("aVL_HRV_CVI", "<f8"),
            ("aVL_HRV_CSI_Modified", "<f8"),
            ("aVL_HRV_SampEn", "<f8"),
            ("aVF_ECG_Rate_Mean", "<f8"),
            ("aVF_HRV_RMSSD", "<f8"),
            ("aVF_HRV_MeanNN", "<f8"),
            ("aVF_HRV_SDNN", "<f8"),
            ("aVF_HRV_SDSD", "<f8"),
            ("aVF_HRV_CVNN", "<f8"),
            ("aVF_HRV_CVSD", "<f8"),
            ("aVF_HRV_MedianNN", "<f8"),
            ("aVF_HRV_MadNN", "<f8"),
            ("aVF_HRV_MCVNN", "<f8"),
            ("aVF_HRV_pNN50", "<f8"),
            ("aVF_HRV_pNN20", "<f8"),
            ("aVF_HRV_TINN", "<f8"),
            ("aVF_HRV_HTI", "<f8"),
            ("aVF_HRV_ULF", "<f8"),
            ("aVF_HRV_VLF", "<f8"),
            ("aVF_HRV_LF", "<f8"),
            ("aVF_HRV_HF", "<f8"),
            ("aVF_HRV_VHF", "<f8"),
            ("aVF_HRV_LFHF", "<f8"),
            ("aVF_HRV_LFn", "<f8"),
            ("aVF_HRV_HFn", "<f8"),
            ("aVF_HRV_LnHF", "<f8"),
            ("aVF_HRV_SD1", "<f8"),
            ("aVF_HRV_SD2", "<f8"),
            ("aVF_HRV_SD2SD1", "<f8"),
            ("aVF_HRV_CSI", "<f8"),
            ("aVF_HRV_CVI", "<f8"),
            ("aVF_HRV_CSI_Modified", "<f8"),
            ("aVF_HRV_SampEn", "<f8"),
            ("V1_ECG_Rate_Mean", "<f8"),
            ("V1_HRV_RMSSD", "<f8"),
            ("V1_HRV_MeanNN", "<f8"),
            ("V1_HRV_SDNN", "<f8"),
            ("V1_HRV_SDSD", "<f8"),
            ("V1_HRV_CVNN", "<f8"),
            ("V1_HRV_CVSD", "<f8"),
            ("V1_HRV_MedianNN", "<f8"),
            ("V1_HRV_MadNN", "<f8"),
            ("V1_HRV_MCVNN", "<f8"),
            ("V1_HRV_pNN50", "<f8"),
            ("V1_HRV_pNN20", "<f8"),
            ("V1_HRV_TINN", "<f8"),
            ("V1_HRV_HTI", "<f8"),
            ("V1_HRV_ULF", "<f8"),
            ("V1_HRV_VLF", "<f8"),
            ("V1_HRV_LF", "<f8"),
            ("V1_HRV_HF", "<f8"),
            ("V1_HRV_VHF", "<f8"),
            ("V1_HRV_LFHF", "<f8"),
            ("V1_HRV_LFn", "<f8"),
            ("V1_HRV_HFn", "<f8"),
            ("V1_HRV_LnHF", "<f8"),
            ("V1_HRV_SD1", "<f8"),
            ("V1_HRV_SD2", "<f8"),
            ("V1_HRV_SD2SD1", "<f8"),
            ("V1_HRV_CSI", "<f8"),
            ("V1_HRV_CVI", "<f8"),
            ("V1_HRV_CSI_Modified", "<f8"),
            ("V1_HRV_SampEn", "<f8"),
            ("V2_ECG_Rate_Mean", "<f8"),
            ("V2_HRV_RMSSD", "<f8"),
            ("V2_HRV_MeanNN", "<f8"),
            ("V2_HRV_SDNN", "<f8"),
            ("V2_HRV_SDSD", "<f8"),
            ("V2_HRV_CVNN", "<f8"),
            ("V2_HRV_CVSD", "<f8"),
            ("V2_HRV_MedianNN", "<f8"),
            ("V2_HRV_MadNN", "<f8"),
            ("V2_HRV_MCVNN", "<f8"),
            ("V2_HRV_pNN50", "<f8"),
            ("V2_HRV_pNN20", "<f8"),
            ("V2_HRV_TINN", "<f8"),
            ("V2_HRV_HTI", "<f8"),
            ("V2_HRV_ULF", "<f8"),
            ("V2_HRV_VLF", "<f8"),
            ("V2_HRV_LF", "<f8"),
            ("V2_HRV_HF", "<f8"),
            ("V2_HRV_VHF", "<f8"),
            ("V2_HRV_LFHF", "<f8"),
            ("V2_HRV_LFn", "<f8"),
            ("V2_HRV_HFn", "<f8"),
            ("V2_HRV_LnHF", "<f8"),
            ("V2_HRV_SD1", "<f8"),
            ("V2_HRV_SD2", "<f8"),
            ("V2_HRV_SD2SD1", "<f8"),
            ("V2_HRV_CSI", "<f8"),
            ("V2_HRV_CVI", "<f8"),
            ("V2_HRV_CSI_Modified", "<f8"),
            ("V2_HRV_SampEn", "<f8"),
            ("V3_ECG_Rate_Mean", "<f8"),
            ("V3_HRV_RMSSD", "<f8"),
            ("V3_HRV_MeanNN", "<f8"),
            ("V3_HRV_SDNN", "<f8"),
            ("V3_HRV_SDSD", "<f8"),
            ("V3_HRV_CVNN", "<f8"),
            ("V3_HRV_CVSD", "<f8"),
            ("V3_HRV_MedianNN", "<f8"),
            ("V3_HRV_MadNN", "<f8"),
            ("V3_HRV_MCVNN", "<f8"),
            ("V3_HRV_pNN50", "<f8"),
            ("V3_HRV_pNN20", "<f8"),
            ("V3_HRV_TINN", "<f8"),
            ("V3_HRV_HTI", "<f8"),
            ("V3_HRV_ULF", "<f8"),
            ("V3_HRV_VLF", "<f8"),
            ("V3_HRV_LF", "<f8"),
            ("V3_HRV_HF", "<f8"),
            ("V3_HRV_VHF", "<f8"),
            ("V3_HRV_LFHF", "<f8"),
            ("V3_HRV_LFn", "<f8"),
            ("V3_HRV_HFn", "<f8"),
            ("V3_HRV_LnHF", "<f8"),
            ("V3_HRV_SD1", "<f8"),
            ("V3_HRV_SD2", "<f8"),
            ("V3_HRV_SD2SD1", "<f8"),
            ("V3_HRV_CSI", "<f8"),
            ("V3_HRV_CVI", "<f8"),
            ("V3_HRV_CSI_Modified", "<f8"),
            ("V3_HRV_SampEn", "<f8"),
            ("V4_ECG_Rate_Mean", "<f8"),
            ("V4_HRV_RMSSD", "<f8"),
            ("V4_HRV_MeanNN", "<f8"),
            ("V4_HRV_SDNN", "<f8"),
            ("V4_HRV_SDSD", "<f8"),
            ("V4_HRV_CVNN", "<f8"),
            ("V4_HRV_CVSD", "<f8"),
            ("V4_HRV_MedianNN", "<f8"),
            ("V4_HRV_MadNN", "<f8"),
            ("V4_HRV_MCVNN", "<f8"),
            ("V4_HRV_pNN50", "<f8"),
            ("V4_HRV_pNN20", "<f8"),
            ("V4_HRV_TINN", "<f8"),
            ("V4_HRV_HTI", "<f8"),
            ("V4_HRV_ULF", "<f8"),
            ("V4_HRV_VLF", "<f8"),
            ("V4_HRV_LF", "<f8"),
            ("V4_HRV_HF", "<f8"),
            ("V4_HRV_VHF", "<f8"),
            ("V4_HRV_LFHF", "<f8"),
            ("V4_HRV_LFn", "<f8"),
            ("V4_HRV_HFn", "<f8"),
            ("V4_HRV_LnHF", "<f8"),
            ("V4_HRV_SD1", "<f8"),
            ("V4_HRV_SD2", "<f8"),
            ("V4_HRV_SD2SD1", "<f8"),
            ("V4_HRV_CSI", "<f8"),
            ("V4_HRV_CVI", "<f8"),
            ("V4_HRV_CSI_Modified", "<f8"),
            ("V4_HRV_SampEn", "<f8"),
            ("V5_ECG_Rate_Mean", "<f8"),
            ("V5_HRV_RMSSD", "<f8"),
            ("V5_HRV_MeanNN", "<f8"),
            ("V5_HRV_SDNN", "<f8"),
            ("V5_HRV_SDSD", "<f8"),
            ("V5_HRV_CVNN", "<f8"),
            ("V5_HRV_CVSD", "<f8"),
            ("V5_HRV_MedianNN", "<f8"),
            ("V5_HRV_MadNN", "<f8"),
            ("V5_HRV_MCVNN", "<f8"),
            ("V5_HRV_pNN50", "<f8"),
            ("V5_HRV_pNN20", "<f8"),
            ("V5_HRV_TINN", "<f8"),
            ("V5_HRV_HTI", "<f8"),
            ("V5_HRV_ULF", "<f8"),
            ("V5_HRV_VLF", "<f8"),
            ("V5_HRV_LF", "<f8"),
            ("V5_HRV_HF", "<f8"),
            ("V5_HRV_VHF", "<f8"),
            ("V5_HRV_LFHF", "<f8"),
            ("V5_HRV_LFn", "<f8"),
            ("V5_HRV_HFn", "<f8"),
            ("V5_HRV_LnHF", "<f8"),
            ("V5_HRV_SD1", "<f8"),
            ("V5_HRV_SD2", "<f8"),
            ("V5_HRV_SD2SD1", "<f8"),
            ("V5_HRV_CSI", "<f8"),
            ("V5_HRV_CVI", "<f8"),
            ("V5_HRV_CSI_Modified", "<f8"),
            ("V5_HRV_SampEn", "<f8"),
            ("V6_ECG_Rate_Mean", "<f8"),
            ("V6_HRV_RMSSD", "<f8"),
            ("V6_HRV_MeanNN", "<f8"),
            ("V6_HRV_SDNN", "<f8"),
            ("V6_HRV_SDSD", "<f8"),
            ("V6_HRV_CVNN", "<f8"),
            ("V6_HRV_CVSD", "<f8"),
            ("V6_HRV_MedianNN", "<f8"),
            ("V6_HRV_MadNN", "<f8"),
            ("V6_HRV_MCVNN", "<f8"),
            ("V6_HRV_pNN50", "<f8"),
            ("V6_HRV_pNN20", "<f8"),
            ("V6_HRV_TINN", "<f8"),
            ("V6_HRV_HTI", "<f8"),
            ("V6_HRV_ULF", "<f8"),
            ("V6_HRV_VLF", "<f8"),
            ("V6_HRV_LF", "<f8"),
            ("V6_HRV_HF", "<f8"),
            ("V6_HRV_VHF", "<f8"),
            ("V6_HRV_LFHF", "<f8"),
            ("V6_HRV_LFn", "<f8"),
            ("V6_HRV_HFn", "<f8"),
            ("V6_HRV_LnHF", "<f8"),
            ("V6_HRV_SD1", "<f8"),
            ("V6_HRV_SD2", "<f8"),
            ("V6_HRV_SD2SD1", "<f8"),
            ("V6_HRV_CSI", "<f8"),
            ("V6_HRV_CVI", "<f8"),
            ("V6_HRV_CSI_Modified", "<f8"),
            ("V6_HRV_SampEn", "<f8"),
        ]

        self.assertEqual(str_arr.shape, (1,))
        self.assertEqual(str_arr.dtype, ref_dtype)
