#!/usr/bin/env bash
# Do not modify by hand. This script is generated!
# Current pwd should be at the main.py level.
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-0\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 0}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": true}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-1\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 1}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": true}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-2\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 2}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": true}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-3\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 3}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": true}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-4\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 4}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": true}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-0\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 0}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": false}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-1\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 1}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": false}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-2\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 2}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": false}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-3\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 3}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": false}"
python3 main.py configs/scikit_learn_hist_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnHistSimultaneous_CustomMultioutput/00-HistGradientBoostingClassifier/cv5-4\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 4}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2], \"convert_nans\": false}"
