#!/usr/bin/env bash
# Do not modify by hand. This script is generated!
# Current pwd should be at the main.py level.
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous/00-RandomForestClassifier/cv5-0\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 0}}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-RandomForestClassifier/cv5-0\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 0}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-RandomForestClassifier/cv5-0\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 0}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous/00-RandomForestClassifier/cv5-1\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 1}}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-RandomForestClassifier/cv5-1\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 1}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-RandomForestClassifier/cv5-1\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 1}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous/00-RandomForestClassifier/cv5-2\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 2}}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-RandomForestClassifier/cv5-2\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 2}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-RandomForestClassifier/cv5-2\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 2}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous/00-RandomForestClassifier/cv5-3\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 3}}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-RandomForestClassifier/cv5-3\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 3}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-RandomForestClassifier/cv5-3\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 3}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous/00-RandomForestClassifier/cv5-4\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 4}}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-RandomForestClassifier/cv5-4\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 4}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-RandomForestClassifier/cv5-4\", \"classifier\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 4}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
