#!/usr/bin/env bash
# Do not modify by hand. This script is generated!
# Current pwd should be at the main.py level.
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-HistGradientBoostingClassifier/cv5-0\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 0}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-HistGradientBoostingClassifier/cv5-0\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 0}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-HistGradientBoostingClassifier/cv5-1\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 1}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-HistGradientBoostingClassifier/cv5-1\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 1}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-HistGradientBoostingClassifier/cv5-2\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 2}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-HistGradientBoostingClassifier/cv5-2\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 2}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-HistGradientBoostingClassifier/cv5-3\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 3}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-HistGradientBoostingClassifier/cv5-3\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 3}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_Multioutput/00-HistGradientBoostingClassifier/cv5-4\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 4}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"use_multioutput\": true}"
python3 main.py configs/scikit_learn_combined_leads/base.json --override "{\"exp_name\": \"PhysioNet2020/ScikitLearnSimultaneous_ClassifierChain-387654012/00-HistGradientBoostingClassifier/cv5-4\", \"classifier\": {\"name\": \"sklearn.ensemble.HistGradientBoostingClassifier\"}, \"cross_validation\": {\"fold\": 5, \"val_offset\": 4}, \"select_from_model\": {\"name\": \"sklearn.ensemble.RandomForestClassifier\"}, \"classifier_chain_order\": [3, 8, 7, 6, 5, 4, 0, 1, 2]}"
